clusterGroup:
  name: prod

  sharedValueFiles:
    - /overrides/values-eso.yaml
    - /overrides/values-user-config.yaml
    - /overrides/values-maas.yaml
    - /overrides/values-gpu.yaml
    - /overrides/values-{{ $.Values.global.clusterPlatform }}-gpu.yaml
    - /overrides/values-code-assistant.yaml
