apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpg.cluster.name }}
  namespace: {{ .Values.cnpg.cluster.namespace }}
spec:
  instances: {{ .Values.cnpg.cluster.instances }}
  storage:
    {{- toYaml .Values.cnpg.cluster.storage | nindent 4 }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.cluster.name }}
      owner: {{ .Values.cnpg.cluster.name }}
  {{- with .Values.cnpg.cluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    dashboard:
      managementState: Managed
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Managed
    llamastackoperator:
      managementState: Managed
---
apiVersion: dscinitialization.opendatahub.io/v2
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  monitoring:
    metrics:
      replicas: 1
      storage:
        retention: 90d
        size: 5Gi
