apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: htpasswd-secret-es
  namespace: openshift-config
  labels:
    {{- include "user-config.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.htpasswd.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: htpasswd-secret
    template:
      type: Opaque
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            {{ `{{- $creds := list }}` }}
            {{ `{{- range $user, $pw := . }}` }}
            {{ `  {{- $creds = append $creds (htpasswd $user $pw "bcrypt") }}` }}
            {{ `{{- end }}` }}
            {{ `htpasswd: {{ $creds | join "\n" | quote }}` }}
  dataFrom:
    - extract:
        key: {{ .Values.htpasswd.vaultKey }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    {{- include "user-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  identityProviders:
    - name: htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret
